
title: Malware Analysis
description: >- # this means to ignore newlines until the next key
  Documenting reverse engineering of malware.

remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - { platform: github,  user_url: "https://github.com/rmceoin" }
    - { platform: mastodon,  user_url: "https://infosec.exchange/@rmceoin" }

plugins:
  - jekyll-remote-theme
  - jekyll-redirect-from
  - jekyll-feed

feed:
  excerpt_only: true
